### ISSUE TITLE
move files

### ISSUE THREAD

**Issue by MiczFlor** [MiczFlor/kinshasa-collection.com#25]
in order to integrate this smoothly to the docmint template folder structure, could you please move the files (and update the relative paths) like this:
- all *.html files that are displayed go into the folder /www/htdocs/
- everything else goes into the folder /www/htdocs/vendor/kingcollection/
- All images and other "static" files go into the folder /www/htdocs/static/

**Comment by MiczFlor** [comment]
Actually, I forgot one thing:
All images and other "static" files go into the folder
/www/htdocs/static/
Including files such as 
- android-chrome-192x192.png
- images for protagonists or episode
- images / logos for sponsors
- PDF files attached to articles

**Comment by MiczFlor** [comment]
The relative paths for icons in the header of HTML files in the texts subfolder are not linking to the right place

**Comment by justmarkup** [comment]
corrected paths for icons for html files in texts folder
