### ISSUE TITLE
video on home page cut off on sides

### ISSUE THREAD

**Issue by MiczFlor** [MiczFlor/kinshasa-collection.com#35]
The video on the home is fullscreen (cover) which is good. But it cuts off a lot on the sides. Can this be changed? So that it responds a bit better to the window size? Do not do this before the launch. Wait for version 0.2 :)

**Comment by justmarkup** [comment]
@MiczFlor Hi Micz, I can not reproduce this, which browser/version are you using. Would also be great if you could attach a screenshot here. Thanks.
